[supervisord]
nodaemon=true
logfile=%(ENV_LOG_DIR)s/supervisord-netns.log
pidfile=%(ENV_LOG_DIR)s/supervisord-netns.pid

[inet_http_server]
port=*:9002

[program:O]
command=ip netns exec O sudo -u %(ENV_MY_USER)s %(ENV_BIN_DIR)s/origin -nodeId O
directory=%(ENV_SRC_DIR)s/origin
autostart=true
autorestart=true
startsecs=5
stdout_logfile=%(ENV_LOG_DIR)s/O.log
redirect_stderr=true

[program:C0]
command=ip netns exec C0 sudo -u %(ENV_MY_USER)s %(ENV_BIN_DIR)s/popcache -originURL http://192.168.88.30:8888/ -nodeId C0 -listenAddr 0.0.0.0:8080
directory=%(ENV_SRC_DIR)s/popcache
autostart=true
autorestart=true
startsecs=5
stdout_logfile=%(ENV_LOG_DIR)s/C0.log
redirect_stderr=true


[program:C0_cache]
command=sudo ip netns exec C0 sudo varnishd -F -a 0.0.0.0:8889 -n /run/varnish-C0 -f %(ENV_SRC_DIR)s/l4lb/vcls/C0.vcl -s malloc,512M
directory=%(ENV_SRC_DIR)s/l4lb
autostart=true
autorestart=true
startsecs=5
stdout_logfile=%(ENV_LOG_DIR)s/C0_cache.log
redirect_stderr=true

[program:C1]
command=ip netns exec C1 sudo -u %(ENV_MY_USER)s %(ENV_BIN_DIR)s/popcache -originURL http://192.168.88.30:8888/ -nodeId C1 -listenAddr 0.0.0.0:8080
directory=%(ENV_SRC_DIR)s/popcache
autostart=true
autorestart=true
startsecs=5
stdout_logfile=%(ENV_LOG_DIR)s/C1.log
redirect_stderr=true


[program:C1_cache]
command=sudo ip netns exec C1 sudo varnishd -F -a 0.0.0.0:8889 -n /run/varnish-C1 -f %(ENV_SRC_DIR)s/l4lb/vcls/C1.vcl -s malloc,512M
directory=%(ENV_SRC_DIR)s/l4lb
autostart=true
autorestart=true
startsecs=5
stdout_logfile=%(ENV_LOG_DIR)s/C1_cache.log
redirect_stderr=true

[program:C2]
command=ip netns exec C2 sudo -u %(ENV_MY_USER)s %(ENV_BIN_DIR)s/popcache -originURL http://192.168.88.30:8888/ -nodeId C2 -listenAddr 0.0.0.0:8080
directory=%(ENV_SRC_DIR)s/popcache
autostart=true
autorestart=true
startsecs=5
stdout_logfile=%(ENV_LOG_DIR)s/C2.log
redirect_stderr=true


[program:C2_cache]
command=sudo ip netns exec C2 sudo varnishd -F -a 0.0.0.0:8889 -n /run/varnish-C2 -f %(ENV_SRC_DIR)s/l4lb/vcls/C2.vcl -s malloc,512M
directory=%(ENV_SRC_DIR)s/l4lb
autostart=true
autorestart=true
startsecs=5
stdout_logfile=%(ENV_LOG_DIR)s/C2_cache.log
redirect_stderr=true

[program:C3]
command=ip netns exec C3 sudo -u %(ENV_MY_USER)s %(ENV_BIN_DIR)s/popcache -originURL http://192.168.88.30:8888/ -nodeId C3 -listenAddr 0.0.0.0:8080
directory=%(ENV_SRC_DIR)s/popcache
autostart=true
autorestart=true
startsecs=5
stdout_logfile=%(ENV_LOG_DIR)s/C3.log
redirect_stderr=true


[program:C3_cache]
command=sudo ip netns exec C3 sudo varnishd -F -a 0.0.0.0:8889 -n /run/varnish-C3 -f %(ENV_SRC_DIR)s/l4lb/vcls/C3.vcl -s malloc,512M
directory=%(ENV_SRC_DIR)s/l4lb
autostart=true
autorestart=true
startsecs=5
stdout_logfile=%(ENV_LOG_DIR)s/C3_cache.log
redirect_stderr=true